openapi: 3.1.0
info:
  title: Mystical GPT API
  version: 1.0.0
  description: |
    This API allows GPT to search mystical PDF documents using semantic search embeddings.

servers:
  - url: https://mystical-gpt-api-658175362050.europe-west1.run.app

x-openai:
  auto_call: true
  call_condition: always
  user_input_parameter: query

paths:
  /search:
    post:
      summary: Semantic document search
      operationId: searchDocs
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
      responses:
        '200':
          description: A list of matching documents
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    title:
                      type: string
                    url:
                      type: string
                    score:
                      type: number
                    snippet:
                      type: string

  /ping:
    get:
      summary: Health check
      operationId: pingCheck
      responses:
        '200':
          description: Service is alive
          content:
            text/plain:
              schema:
                type: string
